### ISSUE TITLE
unbound.conf does not use stubby upstream

### ISSUE THREAD

**Issue by le-ander** [MatthewVance/stubby-docker#12]
Hey there!

Thanks a lot for this great docker image!
I just played around with the docker-compose file and realised that the unbound.sh in the unbound container that is run by the docker-compose file contains a unbound.conf which is different from the one in this repo.

Primarily, the upstream servers in the unbound container that is created from the docker-compose file in this repo:
```
    forward-zone:
        # Forward all queries (except those in cache and local zone) to
        # upstream recursive servers
        name: "."
        # Queries to this forward zone use TLS
        forward-tls-upstream: yes

        # https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

        # Cloudflare
        forward-addr: 1.1.1.1@853#cloudflare-dns.com
        forward-addr: 1.0.0.1@853#cloudflare-dns.com
        #forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
        #forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

        # CleanBrowsing
        forward-addr: 185.228.168.9@853#security-filter-dns.cleanbrowsing.org
        forward-addr: 185.228.169.9@853#security-filter-dns.cleanbrowsing.org
        # forward-addr: 2a0d:2a00:1::2@853#security-filter-dns.cleanbrowsing.org
        # forward-addr: 2a0d:2a00:2::2@853#security-filter-dns.cleanbrowsing.org

        # Quad9
        # forward-addr: 9.9.9.9@853#dns.quad9.net
        # forward-addr: 149.112.112.112@853#dns.quad9.net
        # forward-addr: 2620:fe::fe@853#dns.quad9.net
        # forward-addr: 2620:fe::9@853#dns.quad9.net

        # getdnsapi.net
        # forward-addr: 185.49.141.37@853#getdnsapi.net
        # forward-addr: 2a04:b900:0:100::37@853#getdnsapi.net

        # Surfnet
        # forward-addr: 145.100.185.15@853#dnsovertls.sinodun.com
        # forward-addr: 145.100.185.16@853#dnsovertls1.sinodun.com
        # forward-addr: 2001:610:1:40ba:145:100:185:15@853#dnsovertls.sinodun.com
        # forward-addr: 2001:610:1:40ba:145:100:185:16@853#dnsovertls1.sinodun.com
```

And in the unbound.sh script provided here in the repo:
```
    forward-zone:
        # Forward to Stubby
        name: "."
        forward-addr: @STUBBY@
```

Is this intended?

Thanks a lot in advance!

**Comment by MatthewVance** [comment]
Yes, this is intended. To get the benefits of Stubby and Unbound together,
Unbound must forward to Stubby as the upsteam. Stubby itself forwards to
other upstreams as defined in its YAML file.

**Comment by le-ander** [comment]
Thanks for the quick reply! Makes sense that unbound should be forwarding to stubby. However when I run the compose script provided in this repo, the unbound config that gets created is the top one (i.e. the one directly resolving through cloudflare).

So to use stubby, I have to manually replace the created unbound.conf with the one included in the unbound.sh script in this repo.

Shouldn't unbound automatically create the second config I mentioned above on first run?

**Comment by MatthewVance** [comment]
There was a bug for a bit in this repo where that was the case. It was
fixed a couple of weeks ago. You may need to pull down the latest version.

https://github.com/MatthewVance/stubby-docker/issues/11

**Comment by le-ander** [comment]
Hm, I just checked and I should be on the latest version.

When I execute `docker run mvance/unbound:1.10.1-stubby`
and then check the content of the unbound.sh file with `docker exec <container_id> cat /unbound.sh` There seem to be no pointers to the stubby upstream server in there. I would have expected to find them there.

This is the tail of the /unbound.sh file from the mvance/unbound:1.10.1-stubby container:

```

    ###########################################################################
    # FORWARD ZONE
    ###########################################################################
    forward-zone:
        # Forward all queries (except those in cache and local zone) to
        # upstream recursive servers
        name: "."
        # Queries to this forward zone use TLS
        forward-tls-upstream: yes

        # https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

        # Cloudflare
        forward-addr: 1.1.1.1@853#cloudflare-dns.com
        forward-addr: 1.0.0.1@853#cloudflare-dns.com
        #forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
        #forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

        # CleanBrowsing
        forward-addr: 185.228.168.9@853#security-filter-dns.cleanbrowsing.org
        forward-addr: 185.228.169.9@853#security-filter-dns.cleanbrowsing.org
        # forward-addr: 2a0d:2a00:1::2@853#security-filter-dns.cleanbrowsing.org
        # forward-addr: 2a0d:2a00:2::2@853#security-filter-dns.cleanbrowsing.org

        # Quad9
        # forward-addr: 9.9.9.9@853#dns.quad9.net
        # forward-addr: 149.112.112.112@853#dns.quad9.net
        # forward-addr: 2620:fe::fe@853#dns.quad9.net
        # forward-addr: 2620:fe::9@853#dns.quad9.net

        # getdnsapi.net
        # forward-addr: 185.49.141.37@853#getdnsapi.net
        # forward-addr: 2a04:b900:0:100::37@853#getdnsapi.net

        # Surfnet
        # forward-addr: 145.100.185.15@853#dnsovertls.sinodun.com
        # forward-addr: 145.100.185.16@853#dnsovertls1.sinodun.com
        # forward-addr: 2001:610:1:40ba:145:100:185:15@853#dnsovertls.sinodun.com
        # forward-addr: 2001:610:1:40ba:145:100:185:16@853#dnsovertls1.sinodun.com

remote-control:
    control-enable: no
EOT
fi

mkdir -p /opt/unbound/etc/unbound/dev && \
cp -a /dev/random /dev/urandom /opt/unbound/etc/unbound/dev/

mkdir -p -m 700 /opt/unbound/etc/unbound/var && \
chown _unbound:_unbound /opt/unbound/etc/unbound/var && \
/opt/unbound/sbin/unbound-anchor -a /opt/unbound/etc/unbound/var/root.key

exec /opt/unbound/sbin/unbound -d -c /opt/unbound/etc/unbound/unbound.conf
```

**Comment by MatthewVance** [comment]
That is odd. Let me exec into my locally running version to troubleshoot.

**Comment by MatthewVance** [comment]
Thanks for catching and reporting this. I see the same issue and found the bug. I'm working on a fix and will push the updated mvance/unbound:1.10.1-stubby Docker image after it finishes re-building and I confirm the fix. 

Somehow, I imagined to have the wrong `unbound.sh` file in the folder where I build the Dockerfile locally before pushing the image. All the code in the repo is still correct so I wasn't seeing why it would be copying the configuration into the Unbound container. I always try to be careful to ensure the code I'm building matches the repo, but I failed this time.

**Comment by le-ander** [comment]
Thanks a lot for looking into this!
Looking forward to the fix.

**Comment by MatthewVance** [comment]
It should be working now. Let me know if you're still seeing an issue after re-pulling `mvance/unbound:1.10.1-stubby` from Docker Hub.

This is now what shows in the `/etc/unbound/unbound.conf` file in the mvance/unbound:1.10.1-stubby container:
```
    ###########################################################################
    # FORWARD ZONE
    ###########################################################################
    forward-zone:
        # Forward to Stubby
        name: "."
        forward-addr: 172.22.0.2@8053

remote-control:
  control-enabl
```
