### ISSUE TITLE
Help using custom stubby.xml

### ISSUE THREAD

**Issue by vmstan** [MatthewVance/stubby-docker#13]
What is the proper method for using a custom stubby.xml file? I'd like to use Quad9 instead of Cloudflare. When I attempt to remap the location where the file in the container is, I get errors about being unable to access the file.

```
version: '3'
services:
  stubby:
    image: "mvance/stubby:latest"
    network_mode: bridge
    ports:
     - "8053:8053/udp"
     - "8053:8053/tcp"
    volumes:
     - '/home/vmstan/stubby/config:/opt/stubby/etc/stubby'
    restart: unless-stopped
```

Container logs show:

> [18:35:35.836829] STUBBY: Stubby version: Stubby 0.3.0
> Could not parse config file "/opt/stubby/etc/stubby/stubby.yml": Permission denied

The config folder and the stubby.xml file are both set to chmod 664.
