### ISSUE TITLE
Question about running two public IP addresses

### ISSUE THREAD

**Issue by AnimaI** [MatthewVance/stubby-docker#19]
Hello,
I use the version with the service blockerdns. Everything works .

My server has two public IP addresses, let's call them 1.2.3.4 and 1.2.3.5.
Now I want to run on the second IP address 1.2.3.5 NSD nameserver, I take the Docker from here: https://github.com/hardware/nsd-dnssec

Now NSD Docker tells me that port 53 is already in use, even if I explicitly use IP 1.2.3.5 for the NSD service. Probably Stubby Docker uses both IP addresses.
 
I also tried to use a custom port on Stubby Docker as discussed here: 
https://github.com/MatthewVance/stubby-docker/issues/2

In the process, I changed the docker-compose.yml:
```
version: '3'
services:
  stubby:
    image: "mvance/stubby:latest"
    networks:
     - dns
    restart: unless-stopped
  unbound:
    image: "mvance/unbound:1.12.0-stubby"
    depends_on:
      - "stubby"
    ports:
     - "5353:53/udp"
     - "5353:53/tcp"
    networks:
     - dns
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    restart: unless-stopped

networks:
  dns:
```

Unfortunately, no names can be resolved after this docker-compose.yml. So it does not work like this.

Mention:
I changed the stubby as follows, because I want to use only the service of blockerdns. With the default docker-compose.yml it works as well.

Excerpt of my stubby.yml:
```
####### IPv4 addresses ######
## BlockerDNS 35.245.234.132 and 35.239.229.249
  - address_data: 35.245.234.132
    tls_auth_name: "secret.blockerdns.com"
  - address_data: 35.239.229.249
    tls_auth_name: "secret.blockerdns.com"

## Cloudflare 1.1.1.1 and 1.0.0.1
#  - address_data: 1.1.1.1
#    tls_auth_name: "cloudflare-dns.com"
#  - address_data: 1.0.0.1
#    tls_auth_name: "cloudflare-dns.com"

## Google
#  - address_data: 8.8.8.8
#    tls_auth_name: "dns.google"
#  - address_data: 8.8.4.4
#    tls_auth_name: "dns.google"

all other services are commented out
```

What else can I do?
NSD's Docker is running on the second IP 1.2.3.5. 
How can I bind Stubby Docker to the first IP 1.2.3.4?
Or that Unbound uses a port other than 53?

Can you maybe suggest me a way to solve this?

Thanks a lot in advance!
