### ISSUE TITLE
Difficult running unbound on custom port

### ISSUE THREAD

**Issue by tylerpace** [MatthewVance/stubby-docker#2]
I'm trying to run `stubby-docker` on a nearly default setup except for mapping the `unbound` host port to something other than `53`, but I'm failing to serve DNS requests. 

Here's my `docker-compose.yml`.

```
version: '3'
services:

  stubby:
    container_name: stubby
    image: mvance/stubby:latest
    restart: unless-stopped
    networks:
      - dns

  unbound:
    container_name: unbound
    image: mvance/unbound:1.8.3-stubby
    restart: unless-stopped
    ports:
      - "5353:53/udp"
    networks:
      - dns
    depends_on:
      - stubby
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro

networks:
  dns:
```

And my `docker ps` shows both containers up and running.

```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                          NAMES
3c97dd7ef4f7        mvance/unbound:1.8.3-stubby   "/unbound.sh"            2 minutes ago       Up 2 minutes        53/tcp, 0.0.0.0:5353->53/udp   unbound
37d362184c7e        mvance/stubby:latest          "/opt/stubby/bin/stu…"   3 minutes ago       Up 2 minutes        8053/udp                       stubby
```

But `dig` fails on port `5353`.

```
dig @192.168.1.8 -p 5353 google.com

; <<>> DiG 9.10.6 <<>> @192.168.1.8 -p 5353 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

I think the issue is somewhere in `unbound` because I can successfully `dig` to a manually exposed port `8053` in `stubby`.

```
version: '3'
services:

  stubby:
    container_name: stubby
    image: mvance/stubby:latest
    restart: unless-stopped
    ports:
      - "8053:8053/udp"
    networks:
      - dns

  unbound:
    container_name: unbound
    image: mvance/unbound:1.8.3-stubby
    restart: unless-stopped
    ports:
      - "5353:53/udp"
    networks:
      - dns
    depends_on:
      - stubby
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro

networks:
  dns:
```

`dig` is still unsuccessful on `5353`.

```
dig @192.168.1.8 -p 5353 google.com

; <<>> DiG 9.10.6 <<>> @192.168.1.8 -p 5353 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Bug `dig` is successful on `8053`.

```
dig @192.168.1.8 -p 8053 google.com

; <<>> DiG 9.10.6 <<>> @192.168.1.8 -p 8053 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31684
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1452
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		49	IN	A	216.58.193.78

;; Query time: 52 msec
;; SERVER: 192.168.1.8#8053(192.168.1.8)
;; WHEN: Mon Dec 17 13:19:57 PST 2018
;; MSG SIZE  rcvd: 65
```

Unfortunately, `docker logs unbound` doesn't return anything and my knowledge of `unbound` is minimal. I'm hoping that I'm just overlooking something basic here as all I'm introducing is a port change on the host side of the equation.

**Comment by tylerpace** [comment]
The `53` was a typo. I copy-pasted the wrong `dig` command. I triple checked this time. It's definitely broken when changing the mapped port.

I tried the standalone `unbound` container with the following result.

```
docker run --name unbound-solo -d -p 5353:53/udp mvance/unbound:latest
```

```
docker logs unbound-solo
/opt/unbound/etc/unbound/unbound.conf:206: error: must be a power of 2
/opt/unbound/etc/unbound/unbound.conf:211: error: must be a power of 2
/opt/unbound/etc/unbound/unbound.conf:221: error: must be a power of 2
/opt/unbound/etc/unbound/unbound.conf:248: error: must be a power of 2
read /opt/unbound/etc/unbound/unbound.conf failed: 4 errors in configuration file
[1545093270] unbound[1:0] fatal error: Could not read config file: /opt/unbound/etc/unbound/unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf
```

I'm also struggling to get the vanilla port `53` version to work. It was working, but then at some point in my testing it stopped working. Now, when I try to use the vanilla `docker-compose.yml`, I get the following error.

```
docker-compose -f stubby.yml up -d
Creating network "media-server_dns" with the default driver
Creating stubby ... done
Creating unbound ... error

ERROR: for unbound  Cannot start service unbound: driver failed programming external connectivity on endpoint unbound (1c4c7fc9dd02056910624d5152c26d7aa9d935ce1094caa492c0ae267dc215f2): Error starting userland proxy: Bind for 0.0.0.0:53: unexpected error (Failure EADDRINUSE)
```

But, there's nothing listening or bound to `53`. I've checked with `sudo lsof -i :53` and there are no results. I've restarted the docker service as well. This is all on Mac OSX 10.13.6 with Docker 2.0.0.0-mac81 (engine 18.09.0, compose 1.23.2).

I'll boost the logging levels as mentioned in issue #1 and post results.

**Comment by tylerpace** [comment]
I just saw https://github.com/MatthewVance/unbound-docker/issues/8 over on the standalone `unbound` repo. I wonder if my port mapping issues aren't port mapping issues, but rather `unbound` just not starting due to that issue?

**Comment by MatthewVance** [comment]
Thanks. I'm not at a computer at the moment, but I'm wondering if this is
related to https://github.com/MatthewVance/unbound-docker/issues/8.

I'm curious if the vanilla unbound version works if you use 1.8.1 (it
doesn't use slugs, the thing related to the power of two).

**Comment by MatthewVance** [comment]
Yes, I'm wondering the same thing. You noticed this at about the same time
as me. See the update I sent a moment ago.

**Comment by tylerpace** [comment]
No go with 1.8.1 and nothing in `docker logs` with the default logging level.

```
docker run --name unbound-solo -d -p 5353:53/udp mvance/unbound:1.8.1
80a39401be10ebdd7df8b79a117a0461e7909e01d859321e8ac0488bc9598562
```

```
docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                          NAMES
80a39401be10        mvance/unbound:1.8.1   "/unbound.sh"       22 seconds ago      Up 22 seconds       53/tcp, 0.0.0.0:5353->53/udp   unbound-solo
```

```
dig @192.168.1.8 -p 5353 google.com

; <<>> DiG 9.10.6 <<>> @192.168.1.8 -p 5353 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by MatthewVance** [comment]
Thanks for the update. I'm thinking it's a combination of issues. One is
likely the issue you linked to. I think the other one is more specific to
your setup. I'm not yet sure why. Maybe more verbose logging will help
pinpoint it.

I plan to look into this more closely once I have time and access to my
computer.

**Comment by MatthewVance** [comment]
At a point where I can dig (no pun intended) into this some more. Remapping the port on my Ubuntu 18:04 box worked.

Here's my `docker-compose.yml` file:
```
version: '3'
services:
  stubby:
    image: "mvance/stubby:latest"
    networks:
     - dns
    restart: unless-stopped
  unbound:
    image: "mvance/unbound:1.8.3-stubby"
    depends_on:
      - "stubby"    
    ports:
     - "5353:53/udp"
    networks:
     - dns
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    restart: unless-stopped

networks:
  dns:
```

Here's the result of testing this from a different box:
```
dig @192.168.1.24 -p 5353 google.com

; <<>> DiG 9.10.6 <<>> @192.168.1.24 -p 5353 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58510
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		242	IN	A	74.125.21.100
google.com.		242	IN	A	74.125.21.101
google.com.		242	IN	A	74.125.21.102
google.com.		242	IN	A	74.125.21.113
google.com.		242	IN	A	74.125.21.138
google.com.		242	IN	A	74.125.21.139

;; Query time: 169 msec
;; SERVER: 192.168.1.24#5353(192.168.1.24)
;; WHEN: Mon Dec 17 20:42:53 CST 2018
;; MSG SIZE  rcvd: 135
```
This is the results from `docker ps` after re-running `docker-compose up -d`:
```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                          NAMES
bfa6d5dd6a00        mvance/unbound:1.8.3-stubby   "/unbound.sh"            7 minutes ago       Up 7 minutes        53/tcp, 0.0.0.0:5353->53/udp   stubby-docker_unbound_1
a9366e1a755a        mvance/stubby:latest          "/opt/stubby/bin/stu…"   5 days ago          Up 5 days           8053/udp                       stubby-docker_stubby_1
```

This makes me think this issue is more closely tied to your host than a config issue. I found [old references](https://forums.docker.com/t/port-mappings-are-not-released/10565/20) about port mappings not being immediately released on Docker for Mac. I wonder if that's related to your issue with this working on 53 at one point and not later.

I recommend manually deleting each container (docker rm -v hash) and then each image (docker rmi hash). Next, I'd re-start of the docker service again (and perhaps your Mac as well). After that, hopefully it'll work like it should. 

To increase logging, you need to modify the the exec command in [unbound.sh](https://github.com/MatthewVance/stubby-docker/blob/master/unbound/unbound.sh) to `exec /opt/unbound/sbin/unbound -vv -d -d -c /opt/unbound/etc/unbound/unbound.conf` and run `docker-compose up` (without -d option) to watch the logs in the foreground. 

By the way, I take back my earlier remark about this being related to MatthewVance/unbound-docker#8. I forgot I hadn't ported the `slabs` feature over (turns out to be a good thing).
